language: php
php:
  - 7.1
  - 7.4
addons:
  code_climate:
    repo_token: d2e633c11ce9b2f6cdd21d775d295c9836064eaebe96590c2cb3b2370f893555
before_script:
  - sed -i '/phpdoc/d' composer.json
  - composer install
script:
  - phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/* --standard=PSR2 .
  - ./vendor/bin/phpcs --standard=./vendor/athens/standard/ruleset.xml src
after_script:
  - vendor/bin/test-reporter
